# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1235af9cc38a9c2b17e61e2c9fb5e5ac36a4d316f14ae15407f3b9787384ce0f9c8954a2afab18185e4c9fd72861e0387d582b874050a1aa204d5d365f1d9349

test:
  secret_key_base: 7fc327617d597a15cde350cf961d0a690973824286dfa6e914ea1b0ccfb9183b4048e9e1fedceaaa89979eebd8346c61290af6fb4317f187ff8f068fc8cc9d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
